name: didcomm
packages:
  - .
scripts:
  test:
    name: test
    description: "test with coverage"
    run: dart run coverage:test_with_coverage -- --concurrency=1
    exec:
      concurrency: 1

command:
  version:
    changelogCommitBodies:
      include: true
      onlyBreaking: false
    workspaceChangelog: false
