name: didcomm
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/affinidi/didcomm-dart

environment:
  sdk: ^3.7.2

dependencies:
  analyzer: ^7.4.5
  build: ^2.4.2
  build_runner: ^2.4.15
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  crypto_keys_plus: ^0.5.0
  elliptic: ^0.3.11
  json_annotation: ^4.9.0
  meta: ^1.17.0
  pointycastle: ^4.0.0
  source_gen: ^2.0.0
  ssi: 1.0.0-dev.27
  x25519: ^0.1.1

dev_dependencies:
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
