name: didcomm
description: A Dart package for implementing secure and private communication on your app using DIDComm v2 Messaging protocol.
version: 1.1.0
repository: https://github.com/affinidi/affinidi-didcomm-dart

environment:
  sdk: ^3.6.0

platforms:
  web:
  android:
  ios:
  linux:
  macos:
  windows:

dependencies:
  analyzer: ^7.4.5
  build: ^2.4.2
  build_runner: ^2.4.15
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  crypto_keys_plus: ^0.5.0
  dio: ^5.8.0+1
  elliptic: ^0.3.11
  json_annotation: ^4.9.0
  meta: ^1.17.0
  pointycastle: ^4.0.0
  source_gen: ^2.0.0
  # ssi:
  #   git:
  #     url: https://github.com/affinidi/affinidi-ssi-dart.git
  #     ref: dp-cheqd  
  ssi:
    path: ../affinidi-ssi-dart  
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3
  x25519: ^0.1.1

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  json_serializable: ^6.9.5
  lints: ^5.0.0
  melos: ^6.3.2
  parameterized_test: ^2.0.1
  path: ^1.9.1
  test: ^1.24.0
