name: didcomm
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/affinidi/didcomm-dart

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  analyzer: ^7.4.5
  build: ^2.4.2
  build_runner: ^2.4.15
  json_annotation: ^4.9.0
  source_gen: ^2.0.0
  ssi: ^1.0.0-dev.27
  # path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
