name: check
on:
  pull_request:
jobs:
  dart-pipeline:
    uses: affinidi/pipeline-dart/.github/workflows/check.yaml@main
    secrets: inherit
    env:
      TEST_MEDIATOR_DID: ${{ vars.TEST_MEDIATOR_DID }}
      TEST_ALICE_PRIVATE_KEY_PEM: ${{ vars.TEST_ALICE_PRIVATE_KEY_PEM }}
      TEST_BOB_PRIVATE_KEY_PEM: ${{ vars.TEST_BOB_PRIVATE_KEY_PEM }}

